"""
Diagnosis and AI Inference Models

This module defines the models for storing the results of the YOLO26-M inference.
It strictly validates normalized bounding box coordinates and confidence scores 
before allowing any writes to the Firestore database.
"""

from .recommendation import RecommendationModel
from enum import Enum
from typing import Optional
from uuid import UUID
from pydantic import BaseModel, Field


class SeverityEnum(str, Enum):
    """Enumeration for the severity level of the detected disease."""
    low = "low"
    medium = "medium"
    high = "high"


class DiseaseSnapshotModel(BaseModel):
    """
    A snapshot of the disease details at the time of inference.
    Stored inside the scan document to prevent extra lookups to a master diseases collection.
    """
    diseaseId: str = Field(..., description="Unique ID of the detected disease")
    diseaseName: str = Field(..., description="Disease name in English")
    diseaseNameAr: str = Field(..., description="Disease name in Arabic")
    severity: SeverityEnum = Field(..., description="Severity level of the disease")


class BoundingBoxModel(BaseModel):
    """
    Represents the bounding box drawn around the infected area.
    Strictly constrained to normalized float values between 0.0 and 1.0.
    """
    # Using ge=0.0 (greater or equal) and le=1.0 (less or equal) to strictly enforce normalized coordinates
    x: float = Field(..., ge=0.0, le=1.0, description="Normalized X coordinate of the top-left corner")
    y: float = Field(..., ge=0.0, le=1.0, description="Normalized Y coordinate of the top-left corner")
    width: float = Field(..., ge=0.0, le=1.0, description="Normalized width of the bounding box")
    height: float = Field(..., ge=0.0, le=1.0, description="Normalized height of the bounding box")


class DiagnosisModel(BaseModel):
    """
    The main diagnosis block generated by the YOLO engine.
    Embedded directly into ScanModel.diagnosis.
    """
    diagnosisId: UUID = Field(..., description="Unique UUID for this specific diagnosis event")
    
    # Treatment recommendation generated by the LLM
    recommendation: Optional[RecommendationModel] = Field(
        default=None, 
        description="Bilingual treatment advice. Null if LLM fails."
    )
    
    # Confidence score must be a probability between 0% and 100%
    confidenceScore: float = Field(
        ..., 
        ge=0.0, 
        le=1.0, 
        description="AI confidence score (0.0 to 1.0)"
    )
    
    boundingBox: BoundingBoxModel = Field(..., description="Coordinates for the UI overlay")
    modelVersion: str = Field(..., description="Version of the YOLO model used (e.g., 'YOLO26-M_v1')")
    diseaseSnapshot: DiseaseSnapshotModel = Field(..., description="Details of the identified disease")
    
    # Note: The RecommendationModel (from Task 2.5) will be added here later