"""
Recommendation Data Models

This module defines the recommendation model for agricultural treatments.
It supports bilingual outputs generated by the LLM and enforces the One-Read Rule.
"""

from enum import Enum
from typing import List
from uuid import UUID
from pydantic import BaseModel, Field


class GeneratedByEnum(str, Enum):
    """Tracks the source of the recommendation for auditing purposes."""
    llm = "llm"
    manual = "manual"


class RecommendationModel(BaseModel):
    """
    Embedded document containing the treatment recommendation.
    Nested inside DiagnosisModel to complete the single-document architecture.
    """
    recommendationId: UUID = Field(..., description="Unique UUID for this recommendation")
    
    # Enforcing the bilingual constraint for LLM responses
    treatmentText: str = Field(
        ..., 
        description="Treatment recommendation text in English"
    )
    
    treatmentTextAr: str = Field(
        ..., 
        description="Treatment recommendation text in Arabic"
    )
    
    citedSources: List[str] = Field(
        default_factory=list, 
        description="List of URLs or reference strings, defaults to an empty list"
    )
    
    generatedBy: GeneratedByEnum = Field(
        ..., 
        description="Indicates whether the treatment was generated by AI or manually edited"
    )